name: guided-diffusion
target: ood_tester.guided_diffusion_model.GuidedDiffusionModel
attention_resolutions: "32,16,8"
image_size: 256
input_size: ${input_size}
learn_sigma: True
num_channels: 256
num_head_channels: 64
num_res_blocks: 2
resblock_updown: True
use_fp16: True
use_scale_shift_norm: True
diffusion_steps: 1000
class_cond: False
noise_schedule: "linear"
clip_denoised: True
classifier_scale: 3.0
timestep_respacing: "ddim250"
model_path: "../pretrained/guided-diffusion/256x256_diffusion_uncond.pt"
cutouts_num: 8
cutouts_size: 224
early_stop_steps: 100
skip_first_steps: 100
batch_size: ${denoise_batch_size}
early_stop_metric: null
early_stop_thresh: -1.
forback_skip_diff: 0

use_cam: False
process_method: resize